export const IPC = {
  KUBECONFIG_PICK_FILE: 'kubeconfig:pickFile',
  KUBECONFIG_PARSE_FILE: 'kubeconfig:parseFile',
  KUBECONFIG_PARSE_STRING: 'kubeconfig:parseString',
  KUBECONFIG_PICK_DIRECTORY: 'kubeconfig:pickDirectory',
  KUBECONFIG_SCAN_DIRECTORY: 'kubeconfig:scanDirectory',
  KUBECONFIG_SCAN_DEFAULT: 'kubeconfig:scanDefault',
  KUBECONFIG_READ_SOURCE: 'kubeconfig:readSource',
  KUBECONFIG_WRITE_FILE: 'kubeconfig:writeFile',
  KUBECONFIG_EXPORT_CONTEXT: 'kubeconfig:exportContext',

  CLUSTER_CONNECT: 'cluster:connect',
  CLUSTER_DISCONNECT: 'cluster:disconnect',
  CLUSTER_GET_VERSION: 'cluster:getVersion',
  CLUSTER_LIST_NAMESPACES: 'cluster:listNamespaces',

  RESOURCE_LIST: 'resource:list',
  RESOURCE_WATCH_START: 'resource:watch:start',
  RESOURCE_WATCH_STOP: 'resource:watch:stop',
  RESOURCE_WATCH_EVENT: 'resource:watch:event',
  RESOURCE_WATCH_STATUS: 'resource:watch:status',
  RESOURCE_GET_MANIFEST: 'resource:getManifest',
  RESOURCE_APPLY_MANIFEST: 'resource:applyManifest',
  RESOURCE_CREATE_MANIFEST: 'resource:createManifest',
  RESOURCE_DELETE: 'resource:delete',
  RESOURCE_LIST_EVENTS: 'resource:listEvents',
  RESOURCE_LIST_CLUSTER_EVENTS: 'resource:listClusterEvents',

  SESSION_SET_SCOPE: 'session:setScope',

  CLUSTER_STORE_LIST: 'clusterStore:list',
  CLUSTER_STORE_ADD: 'clusterStore:add',
  CLUSTER_STORE_UPDATE: 'clusterStore:update',
  CLUSTER_STORE_REMOVE: 'clusterStore:remove',
  CLUSTER_STORE_UPSERT_ORG: 'clusterStore:upsertOrg',
  CLUSTER_STORE_SYNC_ORG_IDS: 'clusterStore:syncOrgIds',

  CLUSTER_VPN_LINKS_GET: 'clusterVpn:linksGet',
  CLUSTER_VPN_LINKS_SET: 'clusterVpn:linksSet',
  CLUSTER_VPN_LINKS_REMOVE: 'clusterVpn:linksRemove',

  UI_STATE_GET: 'uiState:get',
  UI_STATE_SET: 'uiState:set',

  METRICS_GET_CLUSTER_SUMMARY: 'metrics:getClusterSummary',
  METRICS_GET_NODE_METRICS: 'metrics:getNodeMetrics',
  METRICS_GET_NODE_RANGE: 'metrics:getNodeRange',
  METRICS_GET_POD_RANGE: 'metrics:getPodRange',
  METRICS_GET_CLUSTER_RANGE: 'metrics:getClusterRange',
  METRICS_GET_HPA_RANGE: 'metrics:getHpaRange',
  METRICS_GET_DEPLOYMENT_RANGE: 'metrics:getDeploymentRange',
  METRICS_GET_NODE_PRESSURE: 'metrics:getNodePressure',

  PROMETHEUS_DISCOVER: 'prometheus:discover',
  PROMETHEUS_GET_STATUS: 'prometheus:getStatus',
  PROMETHEUS_QUERY: 'prometheus:query',
  PROMETHEUS_QUERY_RANGE: 'prometheus:queryRange',

  RBAC_CAN_I: 'rbac:canI',
  RBAC_GET_RESOURCE_PERMISSIONS: 'rbac:getResourcePermissions',

  WORKLOAD_GET_CONTEXT: 'workload:getContext',
  WORKLOAD_GET_PERMISSIONS: 'workload:getPermissions',
  WORKLOAD_SCALE: 'workload:scale',
  WORKLOAD_RESTART: 'workload:restart',
  WORKLOAD_PAUSE_ROLLOUT: 'workload:pauseRollout',
  WORKLOAD_RESUME_ROLLOUT: 'workload:resumeRollout',
  WORKLOAD_ROLLOUT_HISTORY: 'workload:rolloutHistory',
  WORKLOAD_ROLLBACK: 'workload:rollback',
  WORKLOAD_CHANGE_IMAGE: 'workload:changeImage',
  WORKLOAD_SUSPEND_JOB: 'workload:suspendJob',
  WORKLOAD_RESUME_JOB: 'workload:resumeJob',
  WORKLOAD_RERUN_JOB: 'workload:rerunJob',
  WORKLOAD_SUSPEND_CRONJOB: 'workload:suspendCronJob',
  WORKLOAD_RESUME_CRONJOB: 'workload:resumeCronJob',
  WORKLOAD_TRIGGER_CRONJOB: 'workload:triggerCronJob',
  WORKLOAD_DELETE_PODS: 'workload:deletePods',

  APP_GET_INFO: 'app:getInfo',
  APP_GET_WELCOME_STATE: 'app:getWelcomeState',
  APP_SET_WELCOME_SEEN: 'app:setWelcomeSeen',
  APP_SET_SPLASH_SEEN: 'app:setSplashSeen',
  APP_GET_DISPLAY_SETTINGS: 'app:getDisplaySettings',
  APP_SET_DISPLAY_SETTINGS: 'app:setDisplaySettings',

  POD_GET_DETAIL: 'pod:getDetail',
  POD_GET_METRICS: 'pod:getMetrics',
  POD_GET_NETWORK: 'pod:getNetwork',

  POD_LOGS_START: 'pod:logs:start',
  POD_LOGS_STOP: 'pod:logs:stop',
  POD_LOGS_DATA: 'pod:logs:data',
  POD_LOGS_ENDED: 'pod:logs:ended',
  POD_LOGS_DOWNLOAD: 'pod:logs:download',

  POD_EXEC_START: 'pod:exec:start',
  POD_EXEC_INPUT: 'pod:exec:input',
  POD_EXEC_RESIZE: 'pod:exec:resize',
  POD_EXEC_STOP: 'pod:exec:stop',
  POD_EXEC_DATA: 'pod:exec:data',
  POD_EXEC_EXIT: 'pod:exec:exit',

  NODE_EXEC_START: 'node:exec:start',
  NODE_EXEC_INPUT: 'node:exec:input',
  NODE_EXEC_RESIZE: 'node:exec:resize',
  NODE_EXEC_STOP: 'node:exec:stop',

  SERVICE_GET_DETAIL: 'service:getDetail',

  PORT_FORWARD_START_POD: 'portForward:startPod',
  PORT_FORWARD_START_SERVICE: 'portForward:startService',
  PORT_FORWARD_STOP: 'portForward:stop',
  PORT_FORWARD_LIST: 'portForward:list',

  TERMINAL_START: 'terminal:start',
  TERMINAL_INPUT: 'terminal:input',
  TERMINAL_RESIZE: 'terminal:resize',
  TERMINAL_STOP: 'terminal:stop',
  TERMINAL_DATA: 'terminal:data',
  TERMINAL_EXIT: 'terminal:exit',

  DISCOVERY_LIST: 'discovery:list',
  DISCOVERY_LIST_CUSTOM_RESOURCE_KINDS: 'discovery:listCustomResourceKinds',
  DISCOVERY_LIST_DYNAMIC_RESOURCES: 'discovery:listDynamicResources',

  HELM_LIST_RELEASES: 'helm:listReleases',
  HELM_LIST_CHARTS: 'helm:listCharts',
  HELM_GET_HISTORY: 'helm:getHistory',
  HELM_GET_RELEASE_DETAIL: 'helm:getReleaseDetail',
  HELM_ROLLBACK: 'helm:rollback',
  HELM_UNINSTALL_CHART: 'helm:uninstallChart',
  HELM_UNINSTALL_RELEASE: 'helm:uninstallRelease',

  UPDATE_CHECK: 'update:check',
  UPDATE_DOWNLOAD: 'update:download',
  UPDATE_INSTALL: 'update:install',
  UPDATE_SKIP_VERSION: 'update:skipVersion',
  UPDATE_REMIND_LATER: 'update:remindLater',
  UPDATE_GET_STATE: 'update:getState',
  UPDATE_GET_SETTINGS: 'update:getSettings',
  UPDATE_SET_SETTINGS: 'update:setSettings',
  UPDATE_STATE_CHANGED: 'update:stateChanged',
  UPDATE_OPEN_RELEASE_PAGE: 'update:openReleasePage',

  SEARCH_RESOURCES: 'search:resources',

  ENTERPRISE_HTTP: 'enterprise:http',

  VPN_LIST: 'vpn:list',
  VPN_ADD: 'vpn:add',
  VPN_UPDATE: 'vpn:update',
  VPN_REMOVE: 'vpn:remove',
  VPN_PICK_FILE: 'vpn:pickFile',
  VPN_CONNECT: 'vpn:connect',
  VPN_DISCONNECT: 'vpn:disconnect',
  VPN_GET_STATUS: 'vpn:getStatus',
  VPN_SET_FOCUS: 'vpn:setFocus',
  VPN_STATUS_CHANGED: 'vpn:statusChanged',
  VPN_REVEAL: 'vpn:reveal',
  VPN_UPSERT_ORG: 'vpn:upsertOrg',
  VPN_SYNC_ORG_IDS: 'vpn:syncOrgIds',
  VPN_GET_CONFIG: 'vpn:getConfig'
} as const
